# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FliptheNumber' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FliptheNumber
pod 'IQKeyboardManagerSwift'

pod 'AppAuth'
pod 'GoogleSignIn'

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FlagPhoneNumber'
 pod 'AlamofireImage'
pod 'NVActivityIndicatorView'


pod 'Alamofire', '~> 5.1'

 pod 'DropDown'
source 'https://github.com/CocoaPods/Specs.git'
    pod 'Localize' , '~> 2.3.0'


  target 'FliptheNumberTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FliptheNumberUITests' do
    # Pods for testing
  end

end
